### ISSUE TITLE
Links to ARLUT website do not work

### ISSUE THREAD

**Issue by cmconnelly** [jonabbey/Ganymede#2]
I tried clicking the links to go to the Ganymede website at http://www.arlut.utexas.edu/gash2/, but got s 404 error.  Searching for “ganymede” on the ARLUT site also found nothing.  Presumably the Ganymede site has moved somewhere else and the lnks need to be updated.

**Comment by zagarjr** [comment]
Jon Abbey passed away a few years back.  From what I hear, authorization to publicly release ganymede wasn't renewed...

**Comment by cmconnelly** [comment]
From what I can tell, he must have died on or just after November 3, 2014.  Looks like the website stayed up at ARLUT until 2016.
